### ISSUE TITLE
upgrade support Lucene 7.6.0 

### ISSUE THREAD

**Issue by byronhe** [javasoze/clue#68]
`Exception in thread "main" org.apache.lucene.index.IndexFormatTooNewException: Format version is not supported (resource BufferedChecksumIndexInput(MMapIndexInput(path="index/_17p.cfs") [slice=_17p.fnm])): 2 (needs to be between 0 and 1)
	at org.apache.lucene.codecs.CodecUtil.checkHeaderNoMagic(CodecUtil.java:216)
	at org.apache.lucene.codecs.CodecUtil.checkHeader(CodecUtil.java:198)
	at org.apache.lucene.codecs.CodecUtil.checkIndexHeader(CodecUtil.java:255)
	at org.apache.lucene.codecs.lucene60.Lucene60FieldInfosFormat.read(Lucene60FieldInfosFormat.java:117)
	at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:108)
	at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:82)
	at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:65)
	at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:57)
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:688)
	at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:80)
	at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:63)
	at io.dashbase.clue.api.DefaultIndexReaderFactory.refreshReader(DefaultIndexReaderFactory.java:27)
	at io.dashbase.clue.api.DefaultIndexReaderFactory.initialize(DefaultIndexReaderFactory.java:19)
	at io.dashbase.clue.ClueContext.<init>(ClueContext.java:74)
	at io.dashbase.clue.ClueApplication.newContext(ClueApplication.java:38)
	at io.dashbase.clue.ClueApplication.<init>(ClueApplication.java:48)
	at io.dashbase.clue.ClueApplication.main(ClueApplication.java:121)
	Suppressed: org.apache.lucene.index.CorruptIndexException: checksum passed (8d57aea2). possibly transient resource issue, or a Lucene or JVM bug (resource=BufferedChecksumIndexInput
`

**Comment by javasoze** [comment]
master is upgraded to 8.2.0
